# Copy to auth.py and provide the correct keys
consumer_key        = 'XXXXXXXXXXXXXXXXXXXXXXXXX'
consumer_secret     = 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'
access_token        = 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
access_token_secret = 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'





